ted_language_ids = {
    "English": "eng",
    "Bulgarian": "bul",
    "Croatian": "hrv",
    "Czech": "ces",
    "Danish": "dan",
    "Dutch": "nld",
    "Estonian": "est",
    "Finnish": "fin",
    "French": "fra",
    "German": "deu",
    "Greek": "ell",
    "Hungarian": "hun",
    "Irish": "gle",
    "Italian": "ita",
    "Latvian": "lav",
    "Lithuanian": "lit",
    "Maltese": "mlt",
    "Polish": "pol",
    "Portuguese": "por",
    "Romanian": "ron",
    "Slovak": "slk",
    "Slovenian": "slv",
    "Spanish": "spa",
    "Swedish": "swe",
}
ted_default_fields = [
    "notice-identifier",
    "publication-date",
    "notice-title",
    "organisation-name-buyer",  # This is the field we're searching on
    "buyer-identifier",  # Keep this to get org numbers if available
    "procedure-identifier",
    "notice-type",
    "organisation-country-buyer",
]

ted_buyer_details = [
    "organisation-name-buyer",
    "organisation-identifier-buyer",
    "organisation-street-buyer",
    "organisation-city-buyer",
    "organisation-country-buyer",
    "organisation-email-buyer",
    "organisation-tel-buyer",
    "organisation-internet-address-buyer",
]

ted_tender_winner_details = [
    "organisation-name-tenderer",
    "organisation-identifier-tenderer",
    "organisation-country-tenderer",
    "organisation-city-tenderer",
    "organisation-email-tenderer",
    "organisation-tel-tenderer",
    "organisation-internet-address-tenderer",
]

ted_general_metadata_details = [
    "buyer-legal-type",
    "buyer-category",
    "business-name",
    "submission-language",
    "BT-771-Lot",
    "BT-44-Lot",
    "BT-50-Lot",
    "BT-113-Lot",
    "BT-41-Lot",
    "eu-funds-name",
]

ted_notice_details = [
    "notice-identifier",
    "notice-type",
    "notice-subtype",
    "notice-purpose",
    "publication-date",
    "notice-title",
    "announcement-title",
    "announcement-url",
    "links",
    "deadline-receipt-request",
    "deadline",
    "contract-conclusion-date",
    "winner-decision-date",
    "BT-160-Tender",
    "BT-160-Tender-Currency",
    "BT-720-Tender",
    "BT-720-Tender-Currency",
]

tender_financials_detailed = [
    "estimated-value-proc",
    "estimated-value-cur-proc",
    "estimated-value-glo",
    "estimated-value-cur-glo",
    "framework-estimated-value",
    "framework-estimated-value-cur",
    "result-value-notice",
    "result-value-cur-notice",
    "total-value",
    "total-value-cur",
    "TV",
    "TVH",
    "TVL",
]
ted_tender_conclusion_results = [
    "winner-selection-status",
    "non-award-justification",
    "BT-142-LotResult",
    "BT-144-LotResult",
    "BT-119-LotResult",
    "contract-nature",
    "contract-nature-main-proc",
    "contract-nature-subtype",
    "contract-title",
    "contract-url",
    "contract-tender-id",
    "contract-conclusion-date",
    "contract-framework-agreement",
    "received-submissions-type-code",
    "received-submissions-type-val",
    "BT-759-LotResult",
    "BT-686-LotResult",
    "BT-685-LotResult",
    "BT-687-LotResult",
    "BT-636-LotResult",
    "BT-635-LotResult",
    "BT-1118-NoticeResult",
    "BT-118-NoticeResult",
    "BT-161-NoticeResult",
    "BT-156-NoticeResult",
    "modification-justification",
    "modification-description",
]

ted_tender_conclusion_winner_details = [
    "winner-identifier",
    "winner-name",
    "winner-email",
    "winner-country",
    "winner-city",
    "winner-internet-address",
    "winner-size",
    "winner-listed",
    "winner-decision-date",
    "winner-contact-point",
    "tender-identifier",
    "tender-rank",
    "BT-730-Tender",
    "BT-731-Tender",
    "BT-1711-Tender",
    "BT-193-Tender",
    "BT-779-Tender",
    "BT-553-Tender",
    "country-origin",
    "BT-682-Tender",
]


ted_notice_procedure_details = [
    "procedure-type",
    "BT-27-Procedure",
    "BT-31-Procedure",
    "BT-33-Procedure",
    "lots-max-allowed-proc",
    "lots-max-awarded-proc",
    "direct-award-justification-text-proc",
    "procedure-features",
    "procedure-justification",
    "exclusion-grounds",
    "exclusion-grounds-source-proc",
    "selection-criteria-source",
    "BT-271-Procedure",
    "estimated-value-proc",
    "additional-information",
    "additional-info-proc",
    "BT-634-Procedure",
    "BT-756-Procedure",
    "competition-termination-proc",
]
