ted_language_ids = {
    "English": "eng",
    "Bulgarian": "bul",
    "Croatian": "hrv",
    "Czech": "ces",
    "Danish": "dan",
    "Dutch": "nld",
    "Estonian": "est",
    "Finnish": "fin",
    "French": "fra",
    "German": "deu",
    "Greek": "ell",
    "Hungarian": "hun",
    "Irish": "gle",
    "Italian": "ita",
    "Latvian": "lav",
    "Lithuanian": "lit",
    "Maltese": "mlt",
    "Norwegian": "nor",
    "Polish": "pol",
    "Portuguese": "por",
    "Romanian": "ron",
    "Slovak": "slk",
    "Slovenian": "slv",
    "Spanish": "spa",
    "Swedish": "swe",
}
ted_default_fields = [
    "notice-identifier",
    "publication-date",
    "notice-title",
    "organisation-name-buyer",  # This is the field we're searching on
    "buyer-identifier",  # Keep this to get org numbers if available
    "procedure-identifier",
    "notice-type",
    "organisation-country-buyer",
]

ted_buyer_details = [
    "organisation-name-buyer",
    "organisation-identifier-buyer",
    "organisation-street-buyer",
    "organisation-city-buyer",
    "organisation-country-buyer",
    "organisation-email-buyer",
    "organisation-tel-buyer",
    "organisation-internet-address-buyer",
]

ted_tender_winner_details = [
    "organisation-name-tenderer",
    "organisation-identifier-tenderer",
    "organisation-country-tenderer",
    "organisation-city-tenderer",
    "organisation-email-tenderer",
    "organisation-tel-tenderer",
    "organisation-internet-address-tenderer",
]

ted_general_metadata_details = [
    "buyer-legal-type",
    "buyer-category",
    "business-name",
    "submission-language",
    "BT-771-Lot",
    "BT-44-Lot",
    "BT-50-Lot",
    "BT-113-Lot",
    "BT-41-Lot",
    "eu-funds-name",
]

ted_notice_details = [
    "notice-identifier",
    "notice-type",
    "notice-subtype",
    "notice-purpose",
    "publication-date",
    "notice-title",
    "announcement-title",
    "announcement-url",
    "links",
    "deadline-receipt-request",
    "deadline",
    "contract-conclusion-date",
    "winner-decision-date",
    "BT-160-Tender",
    "BT-160-Tender-Currency",
    "BT-720-Tender",
    "BT-720-Tender-Currency",
]

tender_financials_detailed = [
    "estimated-value-proc",
    "estimated-value-cur-proc",
    "estimated-value-glo",
    "estimated-value-cur-glo",
    "framework-estimated-value",
    "framework-estimated-value-cur",
    "result-value-notice",
    "result-value-cur-notice",
    "total-value",
    "total-value-cur",
    "TV",
    "TVH",
    "TVL",
]
ted_tender_conclusion_results = [
    "winner-selection-status",
    "non-award-justification",
    "BT-142-LotResult",
    "BT-144-LotResult",
    "BT-119-LotResult",
    "contract-nature",
    "contract-nature-main-proc",
    "contract-nature-subtype",
    "contract-title",
    "contract-url",
    "contract-tender-id",
    "contract-conclusion-date",
    "contract-framework-agreement",
    "received-submissions-type-code",
    "received-submissions-type-val",
    "BT-759-LotResult",
    "BT-686-LotResult",
    "BT-685-LotResult",
    "BT-687-LotResult",
    "BT-636-LotResult",
    "BT-635-LotResult",
    "BT-1118-NoticeResult",
    "BT-118-NoticeResult",
    "BT-161-NoticeResult",
    "BT-156-NoticeResult",
    "modification-justification",
    "modification-description",
]

ted_tender_conclusion_winner_details = [
    "winner-identifier",
    "winner-name",
    "winner-email",
    "winner-country",
    "winner-city",
    "winner-internet-address",
    "winner-size",
    "winner-listed",
    "winner-decision-date",
    "winner-contact-point",
    "tender-identifier",
    "tender-rank",
    "BT-730-Tender",
    "BT-731-Tender",
    "BT-1711-Tender",
    "BT-193-Tender",
    "BT-779-Tender",
    "BT-553-Tender",
    "country-origin",
    "BT-682-Tender",
]


ted_notice_procedure_details = [
    "procedure-type",
    "BT-27-Procedure",
    "BT-31-Procedure",
    "BT-33-Procedure",
    "lots-max-allowed-proc",
    "lots-max-awarded-proc",
    "direct-award-justification-text-proc",
    "procedure-features",
    "procedure-justification",
    "exclusion-grounds",
    "exclusion-grounds-source-proc",
    "selection-criteria-source",
    "BT-271-Procedure",
    "estimated-value-proc",
    "additional-information",
    "additional-info-proc",
    "BT-634-Procedure",
    "BT-756-Procedure",
    "competition-termination-proc",
]


all_ted_search_tags = [
    "buyer-identifier",
    "buyer-country",
    "buyer-city",
    "buyer-post-code",
    "buyer-email",
    "buyer-internet-address",
    "buyer-profile",
    "buyer-legal-type",
    "buyer-category",
    "authority-main-activity",
    "entity-main-activity",
    "acquiring-cpb-buyer",
    "awarding-cpb-org",
    "buyer-contracting-entity",
    "buyer-group-lead",
    "business-name",
    "business-identifier",
    "business-country",
    "business-email",
    "business-internet-address",
    "business-street",
    "business-city",
    "business-post-code",
    "business-tel",
    "BT-501-Business-European",
    "BT-500-Business-European",
    "registration-date",
    "registration-place-country",
    "registration-place-town",
    "registration-place-postcode",
    "eeig-official-name",
    "eu-registration-number",
    "notice-identifier",
    "publication-number",
    "ojs-number",
    "gazette-issue-id",
    "notice-type",
    "notice-subtype",
    "form-type",
    "notice-purpose",
    "notice-version",
    "publication-date",
    "dispatch-date",
    "dispatch-time",
    "issue-date",
    "announcement-title",
    "announcement-url",
    "notice-title",
    "legal-basis-notice",
    "legal-basis",
    "legal-basis-proc",
    "official-language",
    "change-reason-code",
    "change-notice-version-identifier",
    "change-previous-notice-section-identifier",
    "future-notice",
    "previous-notice-id-proc",
    "customization-id",
    "notice-preferred-publication-date",
    "OPP-010-notice",
    "OPP-011-notice",
    "OPP-012-notice",
    "BT-01-notice",
    "BT-02-notice",
    "BT-03-notice",
    "BT-04-notice",
    "BT-05(a)-notice",
    "BT-05(b)-notice",
    "links",
    "procedure-identifier",
    "internal-identifier-proc",
    "procedure-type",
    "BT-105-Procedure",
    "BT-106-Procedure",
    "procedure-accelerated",
    "BT-21-Procedure",
    "BT-24-Procedure",
    "description-proc",
    "title-proc",
    "BT-22-Procedure",
    "BT-23-Procedure",
    "BT-26(m)-Procedure",
    "BT-27-Procedure",
    "BT-27-Procedure-Currency",
    "BT-31-Procedure",
    "BT-33-Procedure",
    "lots-max-allowed-proc",
    "lots-max-awarded-proc",
    "lots-all-required-proc",
    "direct-award-justification-proc",
    "direct-award-justification-text-proc",
    "procedure-justification",
    "procedure-features",
    "cross-border-law-identifier-proc",
    "cross-border-law-description-proc",
    "competition-termination-proc",
    "procurement-relaunch-proc",
    "exclusion-grounds",
    "exclusion-grounds-source-proc",
    "selection-criteria-source",
    "BT-271-Procedure",
    "estimated-value-proc",
    "additional-info-proc",
    "additional-information",
    "BT-300-procedure",
    "BT-88-Procedure",
    "BT-763-Procedure",
    "BT-756-Procedure",
    "BT-634-Procedure",
    "BT-21-Lot",
    "BT-24-Lot",
    "classification-cpv",
    "BT-23-Lot",
    "BT-44-Lot",
    "BT-50-Lot",
    "BT-51-Lot",
    "BT-58-Lot",
    "BT-113-Lot",
    "BT-41-Lot",
    "BT-52-Lot",
    "eu-funds-name",
    "lot-included-proc",
    "lot-included-glo",
    "identifier-glo",
    "title-glo",
    "additional-info-glo",
    "deadline-receipt-request",
    "deadline",
    "contract-conclusion-date",
    "winner-decision-date",
    "estimated-value-cur-proc",
    "estimated-value-glo",
    "estimated-value-cur-glo",
    "BT-27-Lot",
    "BT-27-Lot-Currency",
    "BT-271-Lot",
    "BT-271-Lot-Currency",
    "framework-estimated-value",
    "framework-estimated-value-cur",
    "framework-maximum-value-glo",
    "framework-value-notice",
    "framework-value-cur-notice",
    "framework-approximate-value-notice",
    "result-value-notice",
    "result-value-cur-notice",
    "total-value",
    "total-value-cur",
    "TV",
    "TVH",
    "TVL",
    "subcontracting-value",
    # "subcontracting-cur",  # unsupported by TED API (UNSUPPORTED_VALUE), see /v3/notices/search
    "subcontracting-percentage",
    "concession-revenue-buyer",
    "concession-revenue-user",
    "BT-160-Tender",
    "BT-160-Tender-Currency",
    "BT-720-Tender",
    "BT-720-Tender-Currency",
    "tender-value",
    "tender-value-cur",
    "tender-value-highest",
    "tender-value-lowest",
    "BT-710-LotResult",
    "BT-710-LotResult-Currency",
    "BT-711-LotResult",
    "BT-711-LotResult-Currency",
    "BT-709-LotResult",
    "BT-660-LotResult",
    "winner-identifier",
    "winner-name",
    "winner-email",
    "winner-country",
    "winner-city",
    "winner-post-code",
    "winner-internet-address",
    "winner-size",
    "winner-person",
    "winner-listed",
    "winner-owner-nationality",
    "winner-contact-point",
    "winner-touchpoint-name",
    "winner-touchpoint-city",
    "winner-touchpoint-country",
    "winner-touchpoint-post-code",
    "winner-touchpoint-internet-address",
    "winner-touchpoint-email",
    "winner-touchpoint-gateway",
    "winner-partname",
    "tendering-party-name",
    "tendering-party-leader",
    "tender-identifier",
    "tender-rank",
    "tender-ranked-res",
    "BT-730-Tender",
    "BT-731-Tender",
    "BT-1711-Tender",
    "BT-193-Tender",
    "OPT-211-Tenderer",
    "BT-553-Tender",
    "BT-779-Tender",
    "BT-682-Tender",
    "country-origin",
    "winner-selection-status",
    "non-award-justification",
    "BT-142-LotResult",
    "BT-144-LotResult",
    "BT-119-LotResult",
    "contract-nature",
    "contract-nature-main-proc",
    "contract-nature-subtype",
    "contract-identifier",
    "contract-title",
    "contract-url",
    "contract-tender-id",
    "contract-framework-agreement",
    "received-submissions-type-code",
    "received-submissions-type-val",
    "BT-759-LotResult",
    "BT-686-LotResult",
    "BT-685-LotResult",
    "BT-687-LotResult",
    "BT-636-LotResult",
    "BT-635-LotResult",
    "sme-glo",
    "BT-1118-NoticeResult",
    "BT-118-NoticeResult",
    "BT-161-NoticeResult",
    "BT-156-NoticeResult",
    "modification-justification",
    "modification-description",
    "submission-language",
    "BT-92-Lot",
    "BT-93-Lot",
    "BT-94-Lot",
    "BT-95-Lot",
    "document-restricted-justification",
    "BT-40-Lot",
    "BT-771-Lot",
    "BT-130-Lot",
    "organisation-identifier-buyer",
    "organisation-name-buyer",
    "organisation-street-buyer",
    "organisation-city-buyer",
    "organisation-country-buyer",
    "organisation-post-code-buyer",
    "organisation-email-buyer",
    "organisation-tel-buyer",
    "organisation-fax-buyer",
    "organisation-internet-address-buyer",
    "organisation-identifier-tenderer",
    "organisation-name-tenderer",
    "organisation-country-tenderer",
    "organisation-city-tenderer",
    "organisation-post-code-tenderer",
    "organisation-email-tenderer",
    "organisation-tel-tenderer",
    "organisation-internet-address-tenderer",
    "organisation-name-subcontractor",
    "organisation-identifier-subcontractor",
    "organisation-country-subcontractor",
    "organisation-email-subcontractor",
    "ubo-name",
    "ubo-email",
    "ubo-country",
    "ubo-city",
    "first-name-ubo",
    "buyer-person",
    "organisation-person-tenderer",
    "cvd-contract-type-res",
    "energy-consumption-res",
    "energy-efficiency-label-res",
    "energy-efficiency-quantity-res",
    "energy-savings-res",
    "vehicle-type",
    "vehicle-type-val-res",
    "kilometers-public-transport-res",
    "kilometer-public-transport",
    "consumption-metric-res",
    "savings-metric-res",
    "foreign-subsidies-measures-res",
    "review-id",
    "review-technical-id",
    "review-date",
    "review-body-id",
    "review-body-type",
    "review-url",
    "review-decision-type",
    "review-title",
    "review-description",
    "review-irregularity-type",
    "buyer-reviewrequests-irregularity-type",
    "buyer-review-compainants-code",
    "buyer-review-compainants-val",
    "review-request-fee",
    "review-request-fee-cur",
    "review-request-decision",
    "review-request-withdrawn",
    "review-request-withdrawn-date",
    "review-request-withdrawn-reasons",
    "review-remedy-type",
    "review-remedy-value",
    "review-remedy-value-cur",
    "review-previous-id",
    "review-notice-section-id",
    "BT-785-Review",
    "BT-796-Review",
    "BT-807-Review",
    "BT-808-Review",
    "review-applicant-id",
    "penalties-rewards-description-res",
    "tender-penalties-res",
    "tender-payment-value-res",
]


def fetch_supported_ted_fields(
    api_url: str = "https://api.ted.europa.eu/v3/notices/search",
    api_key: str | None = None,
    timeout: int = 30,
) -> set[str]:
    """Return the full set of field IDs the TED Search API currently accepts.

    The API has no dedicated "list fields" endpoint, but a request containing an
    unsupported field returns a 400 whose message embeds the complete supported-
    values list. We send one deliberately-invalid field and parse that list out.
    """
    import re
    import requests

    headers = {"Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    resp = requests.post(
        api_url,
        json={
            "query": "*",
            "fields": ["__definitely_not_a_real_field__"],
            "limit": 1,
        },
        headers=headers,
        timeout=timeout,
    )

    payload = resp.json()
    message = payload.get("message", "")
    # message format: "... (supported values are: a,b,c,...)"
    # NB: some field IDs contain parentheses (e.g. BT-05(a)-notice), so match
    # greedily up to the LAST closing paren rather than the first.
    match = re.search(r"supported values are:\s*(.+)\)", message, re.DOTALL)
    if not match:
        raise RuntimeError(
            f"Could not parse supported values from response (status {resp.status_code}): {payload!r}"
        )
    return {v.strip() for v in match.group(1).split(",") if v.strip()}


def validate_ted_fields(
    fields: list[str],
    supported: set[str] | None = None,
    **kwargs,
) -> dict[str, list[str]]:
    """Diff a list of field IDs against what the API supports.

    Returns {"valid": [...], "invalid": [...]}. Pass a precomputed ``supported``
    set to avoid a network call, or let it fetch one via ``fetch_supported_ted_fields``.
    """
    if supported is None:
        supported = fetch_supported_ted_fields(**kwargs)
    valid = [f for f in fields if f in supported]
    invalid = [f for f in fields if f not in supported]
    return {"valid": valid, "invalid": invalid}
